config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "main#index"

  get "/products", to: "products#index"
  get '/products/:id', to: "products#show"
  get '/about/', to: "about#index"
  get '/contact/', to: "contact#index"
  get 'cart', to: "cart#index", as: "cart"
  get "invoice", to: 'order#invoice', as: "invoice"
  get "order", to: 'order#index', as: "order"
  get '/order/:id', to: "order#show"

  post "invoice/place_order", to: 'order#place_order', as: 'place_order'
  post 'cart/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  post 'cart/modify_cart_quantity/:id', to: 'cart#modify_cart_quantity', as: 'modify_cart_quantity'
  delete 'cart/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  before_action :initialize_cart

  def index
    @cart = session[:cart]
    @provinces = Province.all
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart][id] = 1
    flash[:notice] = "Item successfully added to cart."
    redirect_to(request.env["HTTP_REFERER"])
  end

  def remove_from_cart
    id = params[:id].to_s
    session[:cart].delete(id)
    flash[:notice] = "Item successfully deleted from cart."
    redirect_to cart_path
  end

  def modify_cart_quantity
    id = params[:id].to_s
    desired_quantity = params[:quantity].to_i
    desired_quantity = 1 if desired_quantity <= 0
    session[:cart][id] = desired_quantity
    flash[:notice] = "Item quantity modified."
    redirect_to cart_path
  end

  def initialize_cart
    session[:cart] ||= {}
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/index.html.erb
<div class="container">
  <h1 class="text-light">Shopping Cart</h1>

  <% if @cart.empty? %>
    <h2 class="text-light">No items in cart</h2>
  <% else %>
    <% total = 0%>
    
    <ul class="text-dark" style="list-style: none;">
      <% @cart.each do |product|%>
        <li class="bg-light border-dark p-2 my-3">
          <% current_product = Product.find(product[0])%>
          <div class="h4">
            <a href="products/<%= current_product.id %>"><%= current_product.name %></a>  
          </div>

          <div class="h5">
            <% if current_product.sale_price %>
              Price Per Item: $<%= current_product.sale_price %>
              <% total += current_product.sale_price*product[1]%>
            <% else %>
              Price Per Item: $<%= current_product.base_price %>
              <% total += current_product.base_price*product[1]%>
            <% end %>
          </div>

          <div>
            <%= form_with url: modify_cart_quantity_path(product[0]), method: :post do |form|%>  
              
              <div class="my-2">
                <%= form.label :quantity, "Product Quantity:"%>
                <%= form.text_field :quantity, value: product[1], style: "width: 3rem; text-align: right;" %>
                <%= form.submit "Modify Quantity" %> 
              </div>

            <% end %>
          </div>

          <div class="h5">
            <% if current_product.sale_price %>
              Price For All: $<%= sprintf('%.2f', current_product.sale_price * product[1])%>
            <% else %>
              Price For All: $<%= sprintf('%.2f', current_product.base_price * product[1]) %>
            <% end %>
          </div>

          <div class="my-3">
            <%= button_to 'Remove From Cart', remove_from_cart_path(product[0]), method: :delete %>
          </div>
        </li>
      <% end %>
    </ul>

    <h3 class="text-light">Current Order Sub-Total: $<%= sprintf('%.2f', total) %></h3>

    <div class="" style="font-size: 15px;">
      <%= form_with url: "/invoice", method: :get do |form|%>  
        
        <div class="my-2">
          <%= form.label :address, "Address:", class: "mx-0", style: "width: 8rem" %>
          <%= form.text_field :address, class: "w-75", value: current_user.address %>
        </div>

        <div class="my-2">
          <%= form.label :category, "Province:", class: "mx-0", style: "width: 8rem" %>
          <select name="Province" id="province" class="w-75" %>
            <% @provinces.each do |province| %>
              <option value="<%= province.id %>" <% if current_user.province_id == province.id %> selected <% end %>><%= province.name %></option>
            <% end %>
          </select>
        </div>

        <div class="my-2">
          <%= form.label :city, "City:", class: "mx-0", style: "width: 8rem" %>
          <%= form.text_field :city, class: "w-75", value: current_user.city %>
        </div>

        <div class="my-2">
          <%= form.label :zip_code, "Zip Code:", class: "mx-0", style: "width: 8rem" %>
          <%= form.text_field :zip_code, class: "w-75", value: current_user.zip_code %>
        </div>

        <div class="">
          <%= button_to 'Continue to Order', invoice_path, method: :get %> 
        </div>

      <% end %>
    </div>

    <%= button_to 'Keep Shopping', products_path, method: :get %>
  <% end %>
</div>