config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "main#index"

  get "/products", to: "products#index"
  get '/products/:id', to: "products#show"
  get '/about/', to: "about#index"
  get '/contact/', to: "contact#index"
  get 'cart', to: "cart#index", as: "cart"
  get "invoice", to: 'order#invoice', as: "invoice"
  get "order", to: 'order#index', as: "order"
  get '/order/:id', to: "order#show"

  post "invoice/place_order", to: 'order#place_order', as: 'place_order'
  post 'cart/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  post 'cart/modify_cart_quantity/:id', to: 'cart#modify_cart_quantity', as: 'modify_cart_quantity'
  delete 'cart/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class ZipCodeValidator < ActiveModel::Validator
  def validate(record)
    if record.zip_code.match(/^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z][ -]?\d[ABCEGHJ-NPRSTV-Z]\d$/i)
      return
    end

    record.errors.add :base, "Invalid zip code."
  end
end

class Order < ApplicationRecord
  belongs_to :province
  belongs_to :user
  has_many :order_products, dependent: :nullify
  has_many :products, through: :order_products
  validates_associated :order_products

  validates_with ZipCodeValidator
  validates :address, :province, :city, :zip_code, :gst, :pst, :hst, presence: true
  validates :gst, :pst, :hst, numericality: true
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :authenticate_user!

  def invoice

    session[:address_details] = {
      province_id: request.GET["Province"],
      address:     request.GET["address"],
      city:        request.GET["city"],
      zip_code:    request.GET["zip_code"]
    }

    @cart = session[:cart]
    @user = current_user
    @address_details = session[:address_details]
    @province = Province.find(session[:address_details][:province_id])
  end

  def place_order
    address_details = session[:address_details]

    current_province = Province.find(address_details["province_id"])
    current_order = Order.create(address:  address_details["address"],
                                 province: current_province,
                                 city:     address_details["city"],
                                 zip_code: address_details["zip_code"],
                                 user:     current_user,
                                 gst:      current_province.gst,
                                 pst:      current_province.pst,
                                 hst:      current_province.hst)

    if current_order.valid?
      products = session[:cart]

      products.each do |product|
        current_product = Product.find(product[0])
        current_price = current_product.sale_price || current_product.base_price
        current_product.quantity_in_stock = current_product.quantity_in_stock - product[1]
        if current_product.valid?
          OrderProduct.create(quantity: product[1], price: current_price, product: current_product,
                              order: current_order)
          current_product.save
        else
          current_order.order_products.each(&:destroy)
          validation_errors = current_product.errors.full_messages
          flash["alert"] = "Error placing order: #{validation_errors}"
          current_order.destroy
          redirect_to cart_path
          return false
        end
      end

      session[:cart] = {}
      session[:address_details] = {}
      flash[:notice] = "Order with id ##{current_order.id} placed."
      redirect_to root_path
    else
      validation_errors = current_order.errors.full_messages
      flash["alert"] = "Error placing order: #{validation_errors}"
      redirect_to cart_path
    end
  end

  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/index.html.erb
<h1>Order History</h1>

<ul class="text-dark" style="list-style: none;">
  <% @orders.each do |order|%>
    <li class="bg-light border-dark p-2 my-3">
      
      <a href="/order/<%= order.id %>">
        <div class="h4">
          Order with id #<%= order.id %>
        </div>    
      </a>
      
    </li>
  <% end %>
</ul>

app/views/order/invoice.html.erb
<div class="container">
  
  <h1>Confirm Order Details</h1>

  <% if @cart.empty? %>
    <h2 class="text-light">No items in cart</h2>
  <% else %>
    <% sub_total = 0%>

    <ul class="text-dark" style="list-style: none;">
      <% @cart.each do |product|%>
        <li class="bg-light border-dark p-2 my-3">
        
          <% current_product = Product.find(product[0])%>
          
          <% if current_product.sale_price %>
            <% price = current_product.sale_price %>
          <% else %>
            <% price =  current_product.base_price %>
          <% end %>
          
          <div class="h4">
            <%= product[1] %>x <%= current_product.name %> at $<%= price %> each 
            <% sub_total += price*product[1]%>    
          </div>

          <div class="h4">
            <% if current_product.sale_price %>
              $<%= sprintf('%.2f', current_product.sale_price * product[1])%>
            <% else %>
              $<%= sprintf('%.2f', current_product.base_price * product[1]) %>
            <% end %>
          </div>

        </li>
      <% end %>
    </ul>

    <h3 class="text-light">Sub-Total: $<%= sprintf('%.2f', sub_total) %></h3>
    <h3 class="text-light">PST: $<%= sprintf('%.2f', sub_total*@province.pst) %></h3>
    <h3 class="text-light">GST: $<%= sprintf('%.2f', sub_total*@province.gst) %></h3>
    <h3 class="text-light">HST: $<%= sprintf('%.2f', sub_total*@province.hst) %></h3>
    <h3 class="text-light">Total: $<%= sprintf('%.2f', sub_total + (1 + sub_total*@province.pst + sub_total*@province.gst + sub_total*@province.hst)) %></h3>

    <h2>Address Details</h2>
    <ul class="text-light h5 mb-5 p-0" style="list-style: none;">
      <li>Address: <%= @address_details[:address] %></li>
      <li>Province: <%= @province.name %></li>
      <li>City: <%= @address_details[:city] %></li>
      <li>Zip Code: <%= @address_details[:zip_code] %></li>
    </ul>


    <%= button_to 'Place Order', place_order_path, method: :post %>
    <%= button_to 'Return to Cart', cart_path, method: :get %>
  <% end %>


</div>

app/views/order/show.html.erb
<h1>Displaying order with id #<%= @order.id %></h1>

<% sub_total = 0%>

<ul class="text-dark" style="list-style: none;">
  <% @order.order_products.each do |order_product|%>
    <li class="bg-light border-dark p-2 my-3">
    
      <% current_product = order_product.product%>
      
      <div class="h4">
        <%= order_product.quantity %>x <%= current_product.name %> at $<%= order_product.price %> each 
        <% sub_total += order_product.price*order_product.quantity%>    
      </div>

      <div class="h4">
        $<%= sprintf('%.2f', order_product.price * order_product.quantity)%>
      </div>

    </li>
  <% end %>
</ul>

<h3 class="text-light">Sub-Total: $<%= sprintf('%.2f', sub_total) %></h3>
<h3 class="text-light">PST: $<%= sprintf('%.2f', sub_total*@order.pst) %></h3>
<h3 class="text-light">GST: $<%= sprintf('%.2f', sub_total*@order.gst) %></h3>
<h3 class="text-light">HST: $<%= sprintf('%.2f', sub_total*@order.hst) %></h3>
<h3 class="text-light">Total: $<%= sprintf('%.2f', sub_total + (1 + sub_total*@order.pst + sub_total*@order.gst + sub_total*@order.hst)) %></h3>

<h2>Address Details</h2>
<ul class="text-light h5 mb-5 p-0" style="list-style: none;">
  <li>Address: <%= @order.address %></li>
  <li>Province: <%= @order.province.name %></li>
  <li>City: <%= @order.city %></li>
  <li>Zip Code: <%= @order.zip_code %></li>
</ul>


<%= button_to 'Return to Order History', order_path, method: :get %>