config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "main#index"

  get "/products", to: "products#index"
  get '/products/:id', to: "products#show"
  get '/about/', to: "about#index"
  get '/contact/', to: "contact#index"
  get 'cart', to: "cart#index", as: "cart"
  get "invoice", to: 'order#invoice', as: "invoice"
  get "order", to: 'order#index', as: "order"
  get '/order/:id', to: "order#show"

  post "invoice/place_order", to: 'order#place_order', as: 'place_order'
  post 'cart/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  post 'cart/modify_cart_quantity/:id', to: 'cart#modify_cart_quantity', as: 'modify_cart_quantity'
  delete 'cart/remove_from_cart/:id', to: 'cart#remove_from_cart', as: 'remove_from_cart'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/about_info.rb
class AboutInfo < ApplicationRecord
  validates :description, :email, :twitter, :facebook, :instagram, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/order.rb
class ZipCodeValidator < ActiveModel::Validator
  def validate(record)
    if record.zip_code.match(/^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z][ -]?\d[ABCEGHJ-NPRSTV-Z]\d$/i)
      return
    end

    record.errors.add :base, "Invalid zip code."
  end
end

class Order < ApplicationRecord
  belongs_to :province
  belongs_to :user
  has_many :order_products, dependent: :nullify
  has_many :products, through: :order_products
  validates_associated :order_products

  validates_with ZipCodeValidator
  validates :address, :province, :city, :zip_code, :gst, :pst, :hst, presence: true
  validates :gst, :pst, :hst, numericality: true
end

app/models/order_product.rb
class QuantityValidator < ActiveModel::Validator
  def validate(record)
    record.errors.add :base, "Cannot have a negative quantity." if record.quantity <= 0
  end
end

class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, :price, presence: true
  validates :quantity, :price, numericality: true
  validates_with QuantityValidator
end

app/models/product.rb
class ProductQuantityValidator < ActiveModel::Validator
  def validate(record)
    return unless record.quantity_in_stock.negative?

    record.errors.add :base, "#{record.name} has insufficient quantity for this order."
  end
end

class Product < ApplicationRecord
  paginates_per 16

  belongs_to :category
  has_many :order_products, dependent: :nullify
  has_many :orders, through: :order_products

  has_one_attached :image

  validates_with ProductQuantityValidator
  validates :name, :base_price, :quantity_in_stock, presence: true
  validates :quantity_in_stock, :base_price, numericality: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :orders, dependent: :nullify

  validates :name, :gst, :pst, :hst, presence: true
  validates :gst, :pst, :hst, numericality: true
end

app/models/user.rb
class UserZipCodeValidator < ActiveModel::Validator
  def validate(item)
    if item.zip_code &&
       !item.zip_code.match(/^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z][ -]?\d[ABCEGHJ-NPRSTV-Z]\d$/i)
      item.errors.add :base, "Invalid zip code."
    end
  end
end

class UserPhoneNumberValidator < ActiveModel::Validator
  def validate(record)
    if record.phone_number &&
       !record.phone_number.match(/^(\+0?1\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$/i)
      record.errors.add :base, "Invalid phone number."
    end
  end
end

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :province
  has_many :orders, dependent: :nullify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_with UserZipCodeValidator
  validates_with UserPhoneNumberValidator
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about = AboutInfo.first
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  before_action :initialize_cart

  def index
    @cart = session[:cart]
    @provinces = Province.all
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart][id] = 1
    flash[:notice] = "Item successfully added to cart."
    redirect_to(request.env["HTTP_REFERER"])
  end

  def remove_from_cart
    id = params[:id].to_s
    session[:cart].delete(id)
    flash[:notice] = "Item successfully deleted from cart."
    redirect_to cart_path
  end

  def modify_cart_quantity
    id = params[:id].to_s
    desired_quantity = params[:quantity].to_i
    desired_quantity = 1 if desired_quantity <= 0
    session[:cart][id] = desired_quantity
    flash[:notice] = "Item quantity modified."
    redirect_to cart_path
  end

  def initialize_cart
    session[:cart] ||= {}
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :authenticate_user!

  def invoice

    session[:address_details] = {
      province_id: request.GET["Province"],
      address:     request.GET["address"],
      city:        request.GET["city"],
      zip_code:    request.GET["zip_code"]
    }

    @cart = session[:cart]
    @user = current_user
    @address_details = session[:address_details]
    @province = Province.find(session[:address_details][:province_id])
  end

  def place_order
    address_details = session[:address_details]

    current_province = Province.find(address_details["province_id"])
    current_order = Order.create(address:  address_details["address"],
                                 province: current_province,
                                 city:     address_details["city"],
                                 zip_code: address_details["zip_code"],
                                 user:     current_user,
                                 gst:      current_province.gst,
                                 pst:      current_province.pst,
                                 hst:      current_province.hst)

    if current_order.valid?
      products = session[:cart]

      products.each do |product|
        current_product = Product.find(product[0])
        current_price = current_product.sale_price || current_product.base_price
        current_product.quantity_in_stock = current_product.quantity_in_stock - product[1]
        if current_product.valid?
          OrderProduct.create(quantity: product[1], price: current_price, product: current_product,
                              order: current_order)
          current_product.save
        else
          current_order.order_products.each(&:destroy)
          validation_errors = current_product.errors.full_messages
          flash["alert"] = "Error placing order: #{validation_errors}"
          current_order.destroy
          redirect_to cart_path
          return false
        end
      end

      session[:cart] = {}
      session[:address_details] = {}
      flash[:notice] = "Order with id ##{current_order.id} placed."
      redirect_to root_path
    else
      validation_errors = current_order.errors.full_messages
      flash["alert"] = "Error placing order: #{validation_errors}"
      redirect_to cart_path
    end
  end

  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cody's Card Cove</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet"> 
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_importmap_tags %>
  </head>

  <body class="bg-dark text-light">
    <%= render partial: "shared/navbar" %>
    <div class=<%if notice %> "container alert alert-success"<% else %>none<% end %>><%= notice %></div>
    <div class=<%if alert %> "container alert alert-danger"<% else %>none<% end %>><%= alert %></div>
    
    <div class="container" style="font-family: 'Roboto', sans-serif;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-xl bg-dark navbar-dark">
  <div class="container">
    <%= link_to "Cody's Card Cove", root_path, class: "navbar-brand" %>
    <div class="navbar-nav ms-auto">
      <%= link_to "Home", root_path, class: "nav-item nav-link" %>
      <%= link_to "Products", products_path, class: "nav-item nav-link" %>
      <%= link_to "About Us", about_path, class: "nav-item nav-link" %>
      <%= link_to "Contact Us", contact_path, class: "nav-item nav-link" %>
      
      <% if not user_signed_in? %>
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link" %>
        <%= link_to "Sign In", new_user_session_path, class: "nav-item nav-link" %>
      <% else %>
        <%= link_to "Cart (#{session["cart"] ? session["cart"].size : 0})", cart_path, class: "nav-item nav-link" %>
        <%= link_to "Order History", order_path, class: "nav-item nav-link" %>
        <%= link_to "Edit Account", edit_user_registration_path, class: "nav-item nav-link" %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
      <% end %>

    </div>
  </div>
</nav>

app/views/shared/_product_card.html.erb
<a href="products/<%= product.id %>">
  <div class="card my-4 mr-4" style="width: 16rem; font-size: 15px;">
  <h3 class="p-3 text-center"><%= product.name %></h3>
  <p class="card-text text-center"><strong>Category:</strong> <%= product.category.name %></p>
  <% if product.image.present? %>
    <%= image_tag(product.image, alt: product.name, class: "card-img-top", style: "height: 16rem;" ) %>
  <% else %>
    <%= image_tag "No_Image_Available.jpg" %>
  <% end %>
  <div class="card-body mt-4">  
    <p class="card-text text-right">
      <% if product.sale_price %>
        <span class="text-danger"><s>$<%= product.base_price %></s></span>
        <span>$<%= product.sale_price %></span>
      <% else %>
        <span>$<%= product.base_price %></span>
      <% end %>
    </p>
  </div>
  <%= button_to 'Add to Cart', add_to_cart_path(product.id), method: :post %>
  </div>
</a>